# port 配置
server:
  port: 8082
# spring 配置
spring:
  application:
    name: bank2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3313/db_order?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
# eureka 配置
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
