# port 配置
server:
  port: 8081
# spring 配置
spring:
  application:
    name: bank1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3312/db_order?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
# eureka 配置
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    # 配置 eureka 中的 rest template
    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000
# feign 配置
feign:
  okhttp:
    enabled: true
